// Generated by gencpp from file coord_to_lane/JsonToLaneResponse.msg
// DO NOT EDIT!


#ifndef COORD_TO_LANE_MESSAGE_JSONTOLANERESPONSE_H
#define COORD_TO_LANE_MESSAGE_JSONTOLANERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace coord_to_lane
{
template <class ContainerAllocator>
struct JsonToLaneResponse_
{
  typedef JsonToLaneResponse_<ContainerAllocator> Type;

  JsonToLaneResponse_()
    : lanelet_ids()
    , latitudes()
    , longitudes()
    , local_xs()
    , local_ys()
    , headings()  {
    }
  JsonToLaneResponse_(const ContainerAllocator& _alloc)
    : lanelet_ids(_alloc)
    , latitudes(_alloc)
    , longitudes(_alloc)
    , local_xs(_alloc)
    , local_ys(_alloc)
    , headings(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _lanelet_ids_type;
  _lanelet_ids_type lanelet_ids;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _latitudes_type;
  _latitudes_type latitudes;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _longitudes_type;
  _longitudes_type longitudes;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _local_xs_type;
  _local_xs_type local_xs;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _local_ys_type;
  _local_ys_type local_ys;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _headings_type;
  _headings_type headings;





  typedef boost::shared_ptr< ::coord_to_lane::JsonToLaneResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::coord_to_lane::JsonToLaneResponse_<ContainerAllocator> const> ConstPtr;

}; // struct JsonToLaneResponse_

typedef ::coord_to_lane::JsonToLaneResponse_<std::allocator<void> > JsonToLaneResponse;

typedef boost::shared_ptr< ::coord_to_lane::JsonToLaneResponse > JsonToLaneResponsePtr;
typedef boost::shared_ptr< ::coord_to_lane::JsonToLaneResponse const> JsonToLaneResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::coord_to_lane::JsonToLaneResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::coord_to_lane::JsonToLaneResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::coord_to_lane::JsonToLaneResponse_<ContainerAllocator1> & lhs, const ::coord_to_lane::JsonToLaneResponse_<ContainerAllocator2> & rhs)
{
  return lhs.lanelet_ids == rhs.lanelet_ids &&
    lhs.latitudes == rhs.latitudes &&
    lhs.longitudes == rhs.longitudes &&
    lhs.local_xs == rhs.local_xs &&
    lhs.local_ys == rhs.local_ys &&
    lhs.headings == rhs.headings;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::coord_to_lane::JsonToLaneResponse_<ContainerAllocator1> & lhs, const ::coord_to_lane::JsonToLaneResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace coord_to_lane

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::coord_to_lane::JsonToLaneResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coord_to_lane::JsonToLaneResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::coord_to_lane::JsonToLaneResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::coord_to_lane::JsonToLaneResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coord_to_lane::JsonToLaneResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coord_to_lane::JsonToLaneResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::coord_to_lane::JsonToLaneResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b737285eed744467ad49ee7f51ca3326";
  }

  static const char* value(const ::coord_to_lane::JsonToLaneResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb737285eed744467ULL;
  static const uint64_t static_value2 = 0xad49ee7f51ca3326ULL;
};

template<class ContainerAllocator>
struct DataType< ::coord_to_lane::JsonToLaneResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "coord_to_lane/JsonToLaneResponse";
  }

  static const char* value(const ::coord_to_lane::JsonToLaneResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::coord_to_lane::JsonToLaneResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] lanelet_ids\n"
"float64[] latitudes\n"
"float64[] longitudes\n"
"float64[] local_xs\n"
"float64[] local_ys\n"
"float64[] headings\n"
"\n"
;
  }

  static const char* value(const ::coord_to_lane::JsonToLaneResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::coord_to_lane::JsonToLaneResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lanelet_ids);
      stream.next(m.latitudes);
      stream.next(m.longitudes);
      stream.next(m.local_xs);
      stream.next(m.local_ys);
      stream.next(m.headings);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JsonToLaneResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::coord_to_lane::JsonToLaneResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::coord_to_lane::JsonToLaneResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "lanelet_ids: ";
    if (v.lanelet_ids.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.lanelet_ids.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<int32_t>::stream(s, true ? std::string() : indent + "    ", v.lanelet_ids[i]);
    }
    if (v.lanelet_ids.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "latitudes: ";
    if (v.latitudes.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.latitudes.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.latitudes[i]);
    }
    if (v.latitudes.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "longitudes: ";
    if (v.longitudes.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.longitudes.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.longitudes[i]);
    }
    if (v.longitudes.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "local_xs: ";
    if (v.local_xs.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.local_xs.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.local_xs[i]);
    }
    if (v.local_xs.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "local_ys: ";
    if (v.local_ys.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.local_ys.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.local_ys[i]);
    }
    if (v.local_ys.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "headings: ";
    if (v.headings.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.headings.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.headings[i]);
    }
    if (v.headings.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // COORD_TO_LANE_MESSAGE_JSONTOLANERESPONSE_H
