// Generated by gencpp from file coord_to_lane/JsonToLane.msg
// DO NOT EDIT!


#ifndef COORD_TO_LANE_MESSAGE_JSONTOLANE_H
#define COORD_TO_LANE_MESSAGE_JSONTOLANE_H

#include <ros/service_traits.h>


#include <coord_to_lane/JsonToLaneRequest.h>
#include <coord_to_lane/JsonToLaneResponse.h>


namespace coord_to_lane
{

struct JsonToLane
{

typedef JsonToLaneRequest Request;
typedef JsonToLaneResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct JsonToLane
} // namespace coord_to_lane


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::coord_to_lane::JsonToLane > {
  static const char* value()
  {
    return "b737285eed744467ad49ee7f51ca3326";
  }

  static const char* value(const ::coord_to_lane::JsonToLane&) { return value(); }
};

template<>
struct DataType< ::coord_to_lane::JsonToLane > {
  static const char* value()
  {
    return "coord_to_lane/JsonToLane";
  }

  static const char* value(const ::coord_to_lane::JsonToLane&) { return value(); }
};


// service_traits::MD5Sum< ::coord_to_lane::JsonToLaneRequest> should match
// service_traits::MD5Sum< ::coord_to_lane::JsonToLane >
template<>
struct MD5Sum< ::coord_to_lane::JsonToLaneRequest>
{
  static const char* value()
  {
    return MD5Sum< ::coord_to_lane::JsonToLane >::value();
  }
  static const char* value(const ::coord_to_lane::JsonToLaneRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::coord_to_lane::JsonToLaneRequest> should match
// service_traits::DataType< ::coord_to_lane::JsonToLane >
template<>
struct DataType< ::coord_to_lane::JsonToLaneRequest>
{
  static const char* value()
  {
    return DataType< ::coord_to_lane::JsonToLane >::value();
  }
  static const char* value(const ::coord_to_lane::JsonToLaneRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::coord_to_lane::JsonToLaneResponse> should match
// service_traits::MD5Sum< ::coord_to_lane::JsonToLane >
template<>
struct MD5Sum< ::coord_to_lane::JsonToLaneResponse>
{
  static const char* value()
  {
    return MD5Sum< ::coord_to_lane::JsonToLane >::value();
  }
  static const char* value(const ::coord_to_lane::JsonToLaneResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::coord_to_lane::JsonToLaneResponse> should match
// service_traits::DataType< ::coord_to_lane::JsonToLane >
template<>
struct DataType< ::coord_to_lane::JsonToLaneResponse>
{
  static const char* value()
  {
    return DataType< ::coord_to_lane::JsonToLane >::value();
  }
  static const char* value(const ::coord_to_lane::JsonToLaneResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COORD_TO_LANE_MESSAGE_JSONTOLANE_H
