// Generated by gencpp from file coord_to_lane/JsonToLaneRequest.msg
// DO NOT EDIT!


#ifndef COORD_TO_LANE_MESSAGE_JSONTOLANEREQUEST_H
#define COORD_TO_LANE_MESSAGE_JSONTOLANEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace coord_to_lane
{
template <class ContainerAllocator>
struct JsonToLaneRequest_
{
  typedef JsonToLaneRequest_<ContainerAllocator> Type;

  JsonToLaneRequest_()
    {
    }
  JsonToLaneRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::coord_to_lane::JsonToLaneRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::coord_to_lane::JsonToLaneRequest_<ContainerAllocator> const> ConstPtr;

}; // struct JsonToLaneRequest_

typedef ::coord_to_lane::JsonToLaneRequest_<std::allocator<void> > JsonToLaneRequest;

typedef boost::shared_ptr< ::coord_to_lane::JsonToLaneRequest > JsonToLaneRequestPtr;
typedef boost::shared_ptr< ::coord_to_lane::JsonToLaneRequest const> JsonToLaneRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::coord_to_lane::JsonToLaneRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::coord_to_lane::JsonToLaneRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace coord_to_lane

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::coord_to_lane::JsonToLaneRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coord_to_lane::JsonToLaneRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::coord_to_lane::JsonToLaneRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::coord_to_lane::JsonToLaneRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coord_to_lane::JsonToLaneRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coord_to_lane::JsonToLaneRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::coord_to_lane::JsonToLaneRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::coord_to_lane::JsonToLaneRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::coord_to_lane::JsonToLaneRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "coord_to_lane/JsonToLaneRequest";
  }

  static const char* value(const ::coord_to_lane::JsonToLaneRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::coord_to_lane::JsonToLaneRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::coord_to_lane::JsonToLaneRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::coord_to_lane::JsonToLaneRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JsonToLaneRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::coord_to_lane::JsonToLaneRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::coord_to_lane::JsonToLaneRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // COORD_TO_LANE_MESSAGE_JSONTOLANEREQUEST_H
