; Auto-generated. Do not edit!


(cl:in-package coord_to_lane-srv)


;//! \htmlinclude JsonToLane-request.msg.html

(cl:defclass <JsonToLane-request> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass JsonToLane-request (<JsonToLane-request>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <JsonToLane-request>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'JsonToLane-request)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name coord_to_lane-srv:<JsonToLane-request> is deprecated: use coord_to_lane-srv:JsonToLane-request instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <JsonToLane-request>) ostream)
  "Serializes a message object of type '<JsonToLane-request>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <JsonToLane-request>) istream)
  "Deserializes a message object of type '<JsonToLane-request>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<JsonToLane-request>)))
  "Returns string type for a service object of type '<JsonToLane-request>"
  "coord_to_lane/JsonToLaneRequest")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'JsonToLane-request)))
  "Returns string type for a service object of type 'JsonToLane-request"
  "coord_to_lane/JsonToLaneRequest")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<JsonToLane-request>)))
  "Returns md5sum for a message object of type '<JsonToLane-request>"
  "b737285eed744467ad49ee7f51ca3326")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'JsonToLane-request)))
  "Returns md5sum for a message object of type 'JsonToLane-request"
  "b737285eed744467ad49ee7f51ca3326")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<JsonToLane-request>)))
  "Returns full string definition for message of type '<JsonToLane-request>"
  (cl:format cl:nil "~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'JsonToLane-request)))
  "Returns full string definition for message of type 'JsonToLane-request"
  (cl:format cl:nil "~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <JsonToLane-request>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <JsonToLane-request>))
  "Converts a ROS message object to a list"
  (cl:list 'JsonToLane-request
))
;//! \htmlinclude JsonToLane-response.msg.html

(cl:defclass <JsonToLane-response> (roslisp-msg-protocol:ros-message)
  ((lanelet_ids
    :reader lanelet_ids
    :initarg :lanelet_ids
    :type (cl:vector cl:integer)
   :initform (cl:make-array 0 :element-type 'cl:integer :initial-element 0))
   (latitudes
    :reader latitudes
    :initarg :latitudes
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (longitudes
    :reader longitudes
    :initarg :longitudes
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (local_xs
    :reader local_xs
    :initarg :local_xs
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (local_ys
    :reader local_ys
    :initarg :local_ys
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (headings
    :reader headings
    :initarg :headings
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass JsonToLane-response (<JsonToLane-response>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <JsonToLane-response>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'JsonToLane-response)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name coord_to_lane-srv:<JsonToLane-response> is deprecated: use coord_to_lane-srv:JsonToLane-response instead.")))

(cl:ensure-generic-function 'lanelet_ids-val :lambda-list '(m))
(cl:defmethod lanelet_ids-val ((m <JsonToLane-response>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader coord_to_lane-srv:lanelet_ids-val is deprecated.  Use coord_to_lane-srv:lanelet_ids instead.")
  (lanelet_ids m))

(cl:ensure-generic-function 'latitudes-val :lambda-list '(m))
(cl:defmethod latitudes-val ((m <JsonToLane-response>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader coord_to_lane-srv:latitudes-val is deprecated.  Use coord_to_lane-srv:latitudes instead.")
  (latitudes m))

(cl:ensure-generic-function 'longitudes-val :lambda-list '(m))
(cl:defmethod longitudes-val ((m <JsonToLane-response>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader coord_to_lane-srv:longitudes-val is deprecated.  Use coord_to_lane-srv:longitudes instead.")
  (longitudes m))

(cl:ensure-generic-function 'local_xs-val :lambda-list '(m))
(cl:defmethod local_xs-val ((m <JsonToLane-response>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader coord_to_lane-srv:local_xs-val is deprecated.  Use coord_to_lane-srv:local_xs instead.")
  (local_xs m))

(cl:ensure-generic-function 'local_ys-val :lambda-list '(m))
(cl:defmethod local_ys-val ((m <JsonToLane-response>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader coord_to_lane-srv:local_ys-val is deprecated.  Use coord_to_lane-srv:local_ys instead.")
  (local_ys m))

(cl:ensure-generic-function 'headings-val :lambda-list '(m))
(cl:defmethod headings-val ((m <JsonToLane-response>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader coord_to_lane-srv:headings-val is deprecated.  Use coord_to_lane-srv:headings instead.")
  (headings m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <JsonToLane-response>) ostream)
  "Serializes a message object of type '<JsonToLane-response>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'lanelet_ids))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let* ((signed ele) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    ))
   (cl:slot-value msg 'lanelet_ids))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'latitudes))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'latitudes))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'longitudes))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'longitudes))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'local_xs))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'local_xs))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'local_ys))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'local_ys))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'headings))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'headings))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <JsonToLane-response>) istream)
  "Deserializes a message object of type '<JsonToLane-response>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'lanelet_ids) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'lanelet_ids)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296)))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'latitudes) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'latitudes)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'longitudes) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'longitudes)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'local_xs) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'local_xs)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'local_ys) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'local_ys)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'headings) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'headings)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<JsonToLane-response>)))
  "Returns string type for a service object of type '<JsonToLane-response>"
  "coord_to_lane/JsonToLaneResponse")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'JsonToLane-response)))
  "Returns string type for a service object of type 'JsonToLane-response"
  "coord_to_lane/JsonToLaneResponse")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<JsonToLane-response>)))
  "Returns md5sum for a message object of type '<JsonToLane-response>"
  "b737285eed744467ad49ee7f51ca3326")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'JsonToLane-response)))
  "Returns md5sum for a message object of type 'JsonToLane-response"
  "b737285eed744467ad49ee7f51ca3326")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<JsonToLane-response>)))
  "Returns full string definition for message of type '<JsonToLane-response>"
  (cl:format cl:nil "int32[] lanelet_ids~%float64[] latitudes~%float64[] longitudes~%float64[] local_xs~%float64[] local_ys~%float64[] headings~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'JsonToLane-response)))
  "Returns full string definition for message of type 'JsonToLane-response"
  (cl:format cl:nil "int32[] lanelet_ids~%float64[] latitudes~%float64[] longitudes~%float64[] local_xs~%float64[] local_ys~%float64[] headings~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <JsonToLane-response>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'lanelet_ids) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'latitudes) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'longitudes) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'local_xs) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'local_ys) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'headings) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <JsonToLane-response>))
  "Converts a ROS message object to a list"
  (cl:list 'JsonToLane-response
    (cl:cons ':lanelet_ids (lanelet_ids msg))
    (cl:cons ':latitudes (latitudes msg))
    (cl:cons ':longitudes (longitudes msg))
    (cl:cons ':local_xs (local_xs msg))
    (cl:cons ':local_ys (local_ys msg))
    (cl:cons ':headings (headings msg))
))
(cl:defmethod roslisp-msg-protocol:service-request-type ((msg (cl:eql 'JsonToLane)))
  'JsonToLane-request)
(cl:defmethod roslisp-msg-protocol:service-response-type ((msg (cl:eql 'JsonToLane)))
  'JsonToLane-response)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'JsonToLane)))
  "Returns string type for a service object of type '<JsonToLane>"
  "coord_to_lane/JsonToLane")